name: alisim
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - scikit-learn
  - iqtree
  - scikit-bio
  - matplotlib
  - biopython
  - pyyaml
  - fastani
  - sqlite
  - mummer
  - bioconductor-ggtree
  - r-tidyverse
  - r-phangorn
  - r-ape
  - r-svglite
  - r-viridis
  - pandas=2.1.4
  - lastz
  - scipy
  - seaborn
  - mash
  - jax
  - pip
  - pip:
      - -e ../mosaic_method
      - -e .
